-- Seed data: ~50 demo submissions
INSERT INTO submissions(id, uuid, session_id, created_at, optimist, judet, varsta, sex, persoane_intretinere, domeniu) VALUES (1, 'd44416b5-969b-47f9-8bd4-e215398ed426', 'ueedtngu', DATE_SUB(NOW(), INTERVAL 80 DAY), 1, 'Ialomita', 22, 'F', 1, 'HoReCa');
INSERT INTO entries(submission_id, kind, type, amount) VALUES (1, 'datorie', 'credit imobiliar', 125203);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (1, 'asset', 'depozite bancare', 19735);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (1, 'asset', 'imobile', 806682);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (1, 'asset', 'bunuri de valoare', 9415);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (1, 'asset', 'terenuri', 130819);
INSERT INTO submissions(id, uuid, session_id, created_at, optimist, judet, varsta, sex, persoane_intretinere, domeniu) VALUES (2, '3c139b6e-9a34-45b3-9a75-cca27912881e', '5kgk8pnx', DATE_SUB(NOW(), INTERVAL 15 DAY), 1, 'Covasna', 61, 'F', 2, 'IT & Software');
INSERT INTO entries(submission_id, kind, type, amount) VALUES (2, 'datorie', 'card credit', 10778);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (2, 'datorie', 'datorii la stat', 8868);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (2, 'datorie', 'datorii alte persoane', 17098);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (2, 'asset', 'titluri de stat', 60989);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (2, 'asset', 'bunuri de valoare', 10523);
INSERT INTO submissions(id, uuid, session_id, created_at, optimist, judet, varsta, sex, persoane_intretinere, domeniu) VALUES (3, 'ea05596a-13cd-44cd-8bae-585f93a488b9', 'y5u4nkpb', DATE_SUB(NOW(), INTERVAL 85 DAY), 1, 'Maramures', 34, 'M', 1, 'Transport');
INSERT INTO entries(submission_id, kind, type, amount) VALUES (3, 'datorie', 'credit imobiliar', 190320);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (3, 'datorie', 'datorii la stat', 5256);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (3, 'asset', 'bunuri de valoare', 19175);
INSERT INTO submissions(id, uuid, session_id, created_at, optimist, judet, varsta, sex, persoane_intretinere, domeniu) VALUES (4, 'b32db259-d4bb-42dd-b9ee-82ff77573ed4', '3e9xq9vu', DATE_SUB(NOW(), INTERVAL 89 DAY), 1, 'Alba', 65, 'X', 3, 'Pensionar');
INSERT INTO entries(submission_id, kind, type, amount) VALUES (4, 'datorie', 'credit imobiliar', 415505);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (4, 'datorie', 'datorii alte persoane', 1342);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (4, 'asset', 'bunuri de valoare', 25033);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (4, 'asset', 'terenuri', 54800);
INSERT INTO submissions(id, uuid, session_id, created_at, optimist, judet, varsta, sex, persoane_intretinere, domeniu) VALUES (5, 'ac9ec46e-98c3-437f-8ee5-da6bdcaafcd3', 'za7bak26', DATE_SUB(NOW(), INTERVAL 95 DAY), 0, 'Harghita', 33, 'F', 3, 'Altele');
INSERT INTO entries(submission_id, kind, type, amount) VALUES (5, 'datorie', 'credit personal', 31511);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (5, 'datorie', 'credit imobiliar', 129746);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (5, 'datorie', 'card credit', 6191);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (5, 'datorie', 'datorii la stat', 2790);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (5, 'asset', 'bunuri de valoare', 12958);
INSERT INTO submissions(id, uuid, session_id, created_at, optimist, judet, varsta, sex, persoane_intretinere, domeniu) VALUES (6, '32d78a9d-d4af-42c5-b6af-3d9a97769452', 'g8b6xv5m', DATE_SUB(NOW(), INTERVAL 77 DAY), 1, 'Constanta', 40, 'F', 1, 'Antreprenor / SRL');
INSERT INTO entries(submission_id, kind, type, amount) VALUES (6, 'datorie', 'credit imobiliar', 327928);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (6, 'datorie', 'credit SRL', 402145);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (6, 'datorie', 'datorii la stat', 12544);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (6, 'asset', 'titluri de stat', 18388);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (6, 'asset', 'investitii bursa', 202496);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (6, 'asset', 'bunuri de valoare', 53902);
INSERT INTO submissions(id, uuid, session_id, created_at, optimist, judet, varsta, sex, persoane_intretinere, domeniu) VALUES (7, '14c49ded-f7ab-4951-b06b-adf8a4bb2c45', 'b33k9yyj', DATE_SUB(NOW(), INTERVAL 63 DAY), 0, 'Brasov', 45, 'F', 3, 'Altele');
INSERT INTO entries(submission_id, kind, type, amount) VALUES (7, 'datorie', 'credit personal', 68701);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (7, 'datorie', 'credit SRL', 119225);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (7, 'datorie', 'datorii la stat', 16888);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (7, 'asset', 'cryptomonede', 9397);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (7, 'asset', 'imobile', 499662);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (7, 'asset', 'bunuri de valoare', 9610);
INSERT INTO submissions(id, uuid, session_id, created_at, optimist, judet, varsta, sex, persoane_intretinere, domeniu) VALUES (8, 'eb45810a-c47f-4873-94dd-844693a0a76f', 'au662mpu', DATE_SUB(NOW(), INTERVAL 6 DAY), 0, 'Maramures', 24, 'F', 2, 'Agricultura');
INSERT INTO entries(submission_id, kind, type, amount) VALUES (8, 'datorie', 'credit imobiliar', 302679);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (8, 'asset', 'titluri de stat', 7279);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (8, 'asset', 'cryptomonede', 16156);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (8, 'asset', 'imobile', 463319);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (8, 'asset', 'bunuri de valoare', 8561);
INSERT INTO submissions(id, uuid, session_id, created_at, optimist, judet, varsta, sex, persoane_intretinere, domeniu) VALUES (9, '21f52894-ec84-4237-a37e-810a7ee05aa1', 'b4ez2kat', DATE_SUB(NOW(), INTERVAL 104 DAY), 1, 'Bihor', 33, 'X', 3, 'Educatie');
INSERT INTO entries(submission_id, kind, type, amount) VALUES (9, 'datorie', 'credit personal', 56405);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (9, 'datorie', 'credit imobiliar', 327394);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (9, 'datorie', 'credit SRL', 224004);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (9, 'datorie', 'datorii la stat', 18365);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (9, 'asset', 'depozite bancare', 52662);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (9, 'asset', 'titluri de stat', 40187);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (9, 'asset', 'imobile', 262551);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (9, 'asset', 'bunuri de valoare', 47386);
INSERT INTO submissions(id, uuid, session_id, created_at, optimist, judet, varsta, sex, persoane_intretinere, domeniu) VALUES (10, '2c1f5cee-f747-41ce-8790-dd62f8ce69d0', '88jf45vx', DATE_SUB(NOW(), INTERVAL 113 DAY), 1, 'Bihor', 24, 'F', 3, 'Finante & Banking');
INSERT INTO entries(submission_id, kind, type, amount) VALUES (10, 'datorie', 'credit imobiliar', 308215);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (10, 'datorie', 'datorii la stat', 21061);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (10, 'asset', 'titluri de stat', 54325);
INSERT INTO submissions(id, uuid, session_id, created_at, optimist, judet, varsta, sex, persoane_intretinere, domeniu) VALUES (11, '6cedf97c-be7a-43c1-af03-dd5b23c7995c', 'xhap9vbg', DATE_SUB(NOW(), INTERVAL 14 DAY), 1, 'Salaj', 33, 'M', 2, 'Constructii');
INSERT INTO entries(submission_id, kind, type, amount) VALUES (11, 'datorie', 'credit SRL', 200757);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (11, 'datorie', 'card credit', 6227);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (11, 'datorie', 'datorii la stat', 7583);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (11, 'asset', 'bunuri de valoare', 2975);
INSERT INTO submissions(id, uuid, session_id, created_at, optimist, judet, varsta, sex, persoane_intretinere, domeniu) VALUES (12, '628bd493-72c6-4f73-8acb-269a543b1cf0', 'zcrgbwjn', DATE_SUB(NOW(), INTERVAL 113 DAY), 1, 'Ialomita', 38, 'X', 2, 'IT & Software');
INSERT INTO entries(submission_id, kind, type, amount) VALUES (12, 'datorie', 'credit imobiliar', 515185);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (12, 'datorie', 'credit SRL', 96308);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (12, 'datorie', 'card credit', 2776);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (12, 'datorie', 'datorii la stat', 23523);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (12, 'asset', 'cryptomonede', 11439);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (12, 'asset', 'bunuri de valoare', 30320);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (12, 'asset', 'terenuri', 27433);
INSERT INTO submissions(id, uuid, session_id, created_at, optimist, judet, varsta, sex, persoane_intretinere, domeniu) VALUES (13, 'a2024d3e-3155-44c3-a0ab-70cf22f581ce', 'rsd6e6kx', DATE_SUB(NOW(), INTERVAL 47 DAY), 1, 'Cluj', 39, 'M', 0, 'Freelance');
INSERT INTO entries(submission_id, kind, type, amount) VALUES (13, 'datorie', 'credit imobiliar', 391534);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (13, 'datorie', 'credit SRL', 52717);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (13, 'datorie', 'datorii la stat', 34178);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (13, 'asset', 'cryptomonede', 107166);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (13, 'asset', 'imobile', 1383494);
INSERT INTO submissions(id, uuid, session_id, created_at, optimist, judet, varsta, sex, persoane_intretinere, domeniu) VALUES (14, '2eaac21c-1104-4325-90b2-634e13141190', 'g6amakgk', DATE_SUB(NOW(), INTERVAL 73 DAY), 1, 'Caras-Severin', 61, 'F', 4, 'Freelance');
INSERT INTO entries(submission_id, kind, type, amount) VALUES (14, 'datorie', 'credit personal', 63800);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (14, 'datorie', 'credit SRL', 188453);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (14, 'datorie', 'card credit', 7059);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (14, 'datorie', 'datorii alte persoane', 27566);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (14, 'asset', 'investitii bursa', 98313);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (14, 'asset', 'imobile', 498675);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (14, 'asset', 'bunuri de valoare', 19518);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (14, 'asset', 'terenuri', 93179);
INSERT INTO submissions(id, uuid, session_id, created_at, optimist, judet, varsta, sex, persoane_intretinere, domeniu) VALUES (15, '65fca1f8-6f85-4944-9797-68824702fd4b', 'bm33zdcv', DATE_SUB(NOW(), INTERVAL 57 DAY), 0, 'Mures', 28, 'X', 2, 'Educatie');
INSERT INTO entries(submission_id, kind, type, amount) VALUES (15, 'datorie', 'credit personal', 24864);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (15, 'datorie', 'credit SRL', 97002);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (15, 'datorie', 'card credit', 4610);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (15, 'datorie', 'datorii alte persoane', 1420);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (15, 'asset', 'cryptomonede', 20886);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (15, 'asset', 'bunuri de valoare', 31377);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (15, 'asset', 'terenuri', 92650);
INSERT INTO submissions(id, uuid, session_id, created_at, optimist, judet, varsta, sex, persoane_intretinere, domeniu) VALUES (16, '26076deb-1111-4c61-a71d-753e64ba0163', '9cwbv3dj', DATE_SUB(NOW(), INTERVAL 19 DAY), 0, 'Olt', 39, 'M', 4, 'Sanatate');
INSERT INTO entries(submission_id, kind, type, amount) VALUES (16, 'datorie', 'credit SRL', 76866);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (16, 'asset', 'investitii bursa', 38608);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (16, 'asset', 'cryptomonede', 26669);
INSERT INTO submissions(id, uuid, session_id, created_at, optimist, judet, varsta, sex, persoane_intretinere, domeniu) VALUES (17, '0f958dc2-26be-45d8-acde-5dd493cf99a7', 'nqa9g9fx', DATE_SUB(NOW(), INTERVAL 98 DAY), 1, 'Arges', 42, 'M', 3, 'Altele');
INSERT INTO entries(submission_id, kind, type, amount) VALUES (17, 'datorie', 'credit personal', 48285);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (17, 'datorie', 'card credit', 7966);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (17, 'asset', 'cryptomonede', 71468);
INSERT INTO submissions(id, uuid, session_id, created_at, optimist, judet, varsta, sex, persoane_intretinere, domeniu) VALUES (18, 'b199da8a-ee9d-400f-87b0-e273a5c84e7c', '98ug25uw', DATE_SUB(NOW(), INTERVAL 0 DAY), 1, 'Covasna', 40, 'F', 3, 'Altele');
INSERT INTO entries(submission_id, kind, type, amount) VALUES (18, 'datorie', 'credit personal', 20625);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (18, 'asset', 'titluri de stat', 87473);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (18, 'asset', 'investitii bursa', 73630);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (18, 'asset', 'imobile', 334024);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (18, 'asset', 'terenuri', 62333);
INSERT INTO submissions(id, uuid, session_id, created_at, optimist, judet, varsta, sex, persoane_intretinere, domeniu) VALUES (19, 'fb4cd596-3d84-4c53-9664-df968f606eb0', '3ctjcd9n', DATE_SUB(NOW(), INTERVAL 46 DAY), 0, 'Olt', 61, 'F', 2, 'Student');
INSERT INTO entries(submission_id, kind, type, amount) VALUES (19, 'datorie', 'credit personal', 26870);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (19, 'datorie', 'credit imobiliar', 274438);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (19, 'datorie', 'credit SRL', 82330);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (19, 'datorie', 'datorii alte persoane', 12223);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (19, 'asset', 'depozite bancare', 10317);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (19, 'asset', 'titluri de stat', 18515);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (19, 'asset', 'imobile', 416384);
INSERT INTO submissions(id, uuid, session_id, created_at, optimist, judet, varsta, sex, persoane_intretinere, domeniu) VALUES (20, '7d4a2876-0098-4db7-be84-76a54cc72653', 'n8bwd7nr', DATE_SUB(NOW(), INTERVAL 113 DAY), 0, 'Bacau', 33, 'M', 3, 'Industrie');
INSERT INTO entries(submission_id, kind, type, amount) VALUES (20, 'datorie', 'credit SRL', 16914);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (20, 'asset', 'cryptomonede', 10604);
INSERT INTO submissions(id, uuid, session_id, created_at, optimist, judet, varsta, sex, persoane_intretinere, domeniu) VALUES (21, 'b78b5ebc-08b2-432f-aa9f-140d7f3ab78e', 'arn9v3ms', DATE_SUB(NOW(), INTERVAL 6 DAY), 0, 'Salaj', 66, 'M', 0, 'Sanatate');
INSERT INTO entries(submission_id, kind, type, amount) VALUES (21, 'datorie', 'credit personal', 24656);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (21, 'datorie', 'credit imobiliar', 239564);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (21, 'datorie', 'credit SRL', 115180);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (21, 'datorie', 'datorii la stat', 14459);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (21, 'asset', 'titluri de stat', 10186);
INSERT INTO submissions(id, uuid, session_id, created_at, optimist, judet, varsta, sex, persoane_intretinere, domeniu) VALUES (22, '7e492afa-24b8-4bd3-9226-0433346219fa', 'sz6wpkcw', DATE_SUB(NOW(), INTERVAL 53 DAY), 1, 'Timis', 23, 'X', 1, 'Transport');
INSERT INTO entries(submission_id, kind, type, amount) VALUES (22, 'datorie', 'credit personal', 77001);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (22, 'datorie', 'card credit', 11628);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (22, 'asset', 'investitii bursa', 18125);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (22, 'asset', 'imobile', 826477);
INSERT INTO submissions(id, uuid, session_id, created_at, optimist, judet, varsta, sex, persoane_intretinere, domeniu) VALUES (23, '9eb051cb-141c-4705-a433-a470885effcc', 'km423v4s', DATE_SUB(NOW(), INTERVAL 45 DAY), 1, 'Buzau', 67, 'F', 3, 'Freelance');
INSERT INTO entries(submission_id, kind, type, amount) VALUES (23, 'datorie', 'card credit', 6241);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (23, 'datorie', 'datorii la stat', 12904);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (23, 'datorie', 'datorii alte persoane', 29553);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (23, 'asset', 'depozite bancare', 27471);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (23, 'asset', 'imobile', 170296);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (23, 'asset', 'bunuri de valoare', 9445);
INSERT INTO submissions(id, uuid, session_id, created_at, optimist, judet, varsta, sex, persoane_intretinere, domeniu) VALUES (24, 'd845e7e5-6df5-425d-bbb4-0c4677d494f9', 'g5ycbnah', DATE_SUB(NOW(), INTERVAL 104 DAY), 0, 'Timis', 49, 'F', 0, 'Comert');
INSERT INTO entries(submission_id, kind, type, amount) VALUES (24, 'datorie', 'credit personal', 69672);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (24, 'datorie', 'datorii la stat', 22684);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (24, 'asset', 'titluri de stat', 53311);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (24, 'asset', 'cryptomonede', 59237);
INSERT INTO submissions(id, uuid, session_id, created_at, optimist, judet, varsta, sex, persoane_intretinere, domeniu) VALUES (25, '48b9a628-d7c7-42b6-9033-9e2256a0e0ec', '7ukme6ar', DATE_SUB(NOW(), INTERVAL 99 DAY), 1, 'Tulcea', 32, 'F', 1, 'Antreprenor / SRL');
INSERT INTO entries(submission_id, kind, type, amount) VALUES (25, 'datorie', 'datorii la stat', 5753);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (25, 'datorie', 'datorii alte persoane', 23631);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (25, 'asset', 'titluri de stat', 59165);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (25, 'asset', 'investitii bursa', 83910);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (25, 'asset', 'imobile', 408190);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (25, 'asset', 'terenuri', 105974);
INSERT INTO submissions(id, uuid, session_id, created_at, optimist, judet, varsta, sex, persoane_intretinere, domeniu) VALUES (26, '44cd00b1-2e45-470f-a6aa-9006cf44208a', 'v48r7p8g', DATE_SUB(NOW(), INTERVAL 89 DAY), 0, 'Prahova', 57, 'F', 1, 'Constructii');
INSERT INTO entries(submission_id, kind, type, amount) VALUES (26, 'datorie', 'credit personal', 35727);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (26, 'datorie', 'credit SRL', 74354);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (26, 'datorie', 'card credit', 6377);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (26, 'datorie', 'datorii alte persoane', 14948);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (26, 'asset', 'imobile', 295876);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (26, 'asset', 'terenuri', 124717);
INSERT INTO submissions(id, uuid, session_id, created_at, optimist, judet, varsta, sex, persoane_intretinere, domeniu) VALUES (27, 'e665b180-a740-4f9f-951d-ee7adb9a65f4', '98nwu9dg', DATE_SUB(NOW(), INTERVAL 75 DAY), 0, 'Ilfov', 63, 'X', 2, 'Transport');
INSERT INTO entries(submission_id, kind, type, amount) VALUES (27, 'datorie', 'credit imobiliar', 310931);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (27, 'datorie', 'credit SRL', 153597);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (27, 'asset', 'depozite bancare', 36873);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (27, 'asset', 'titluri de stat', 8797);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (27, 'asset', 'imobile', 708194);
INSERT INTO submissions(id, uuid, session_id, created_at, optimist, judet, varsta, sex, persoane_intretinere, domeniu) VALUES (28, '7db33e95-a2e3-4edb-90b6-bc247b755b6a', 'k47m5gda', DATE_SUB(NOW(), INTERVAL 104 DAY), 1, 'Timis', 31, 'X', 3, 'Antreprenor / SRL');
INSERT INTO entries(submission_id, kind, type, amount) VALUES (28, 'datorie', 'credit imobiliar', 510313);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (28, 'datorie', 'credit SRL', 268292);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (28, 'datorie', 'card credit', 9181);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (28, 'asset', 'investitii bursa', 113874);
INSERT INTO submissions(id, uuid, session_id, created_at, optimist, judet, varsta, sex, persoane_intretinere, domeniu) VALUES (29, 'cac789c9-dd52-4809-b225-8f9c5ca6bb70', 'anazw9x4', DATE_SUB(NOW(), INTERVAL 119 DAY), 1, 'Olt', 29, 'X', 3, 'Sanatate');
INSERT INTO entries(submission_id, kind, type, amount) VALUES (29, 'datorie', 'credit personal', 60463);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (29, 'datorie', 'credit imobiliar', 434442);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (29, 'datorie', 'credit SRL', 41734);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (29, 'datorie', 'datorii alte persoane', 15293);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (29, 'asset', 'cryptomonede', 25668);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (29, 'asset', 'terenuri', 126499);
INSERT INTO submissions(id, uuid, session_id, created_at, optimist, judet, varsta, sex, persoane_intretinere, domeniu) VALUES (30, 'e990b0e5-158b-4fd3-bf7d-f90ad0bce655', 'k4r5zzk3', DATE_SUB(NOW(), INTERVAL 59 DAY), 1, 'Vaslui', 67, 'F', 0, 'Altele');
INSERT INTO entries(submission_id, kind, type, amount) VALUES (30, 'datorie', 'credit personal', 40464);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (30, 'datorie', 'credit imobiliar', 232304);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (30, 'asset', 'titluri de stat', 28961);
INSERT INTO submissions(id, uuid, session_id, created_at, optimist, judet, varsta, sex, persoane_intretinere, domeniu) VALUES (31, 'bf881fa0-727d-4306-b65b-893fa65692c2', '3bth47wz', DATE_SUB(NOW(), INTERVAL 17 DAY), 0, 'Constanta', 44, 'M', 3, 'Freelance');
INSERT INTO entries(submission_id, kind, type, amount) VALUES (31, 'datorie', 'credit personal', 48370);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (31, 'datorie', 'credit imobiliar', 196935);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (31, 'datorie', 'credit SRL', 238954);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (31, 'datorie', 'datorii alte persoane', 11553);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (31, 'asset', 'depozite bancare', 122904);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (31, 'asset', 'investitii bursa', 121253);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (31, 'asset', 'cryptomonede', 25911);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (31, 'asset', 'bunuri de valoare', 54962);
INSERT INTO submissions(id, uuid, session_id, created_at, optimist, judet, varsta, sex, persoane_intretinere, domeniu) VALUES (32, 'd4d2fdf4-6561-4b8f-a11f-a396d5793790', 'r64qs3ph', DATE_SUB(NOW(), INTERVAL 104 DAY), 1, 'Constanta', 61, 'F', 3, 'Antreprenor / SRL');
INSERT INTO entries(submission_id, kind, type, amount) VALUES (32, 'datorie', 'credit imobiliar', 671179);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (32, 'datorie', 'credit SRL', 48616);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (32, 'datorie', 'datorii la stat', 1088);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (32, 'asset', 'terenuri', 192129);
INSERT INTO submissions(id, uuid, session_id, created_at, optimist, judet, varsta, sex, persoane_intretinere, domeniu) VALUES (33, '01d2d898-3204-441b-91ab-583139df9da7', 'akxhnc6e', DATE_SUB(NOW(), INTERVAL 22 DAY), 0, 'Calarasi', 42, 'F', 4, 'Student');
INSERT INTO entries(submission_id, kind, type, amount) VALUES (33, 'datorie', 'datorii alte persoane', 17600);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (33, 'asset', 'depozite bancare', 22653);
INSERT INTO submissions(id, uuid, session_id, created_at, optimist, judet, varsta, sex, persoane_intretinere, domeniu) VALUES (34, 'f302985a-a810-4c8b-8c0a-2236120287c7', 'bkprgda8', DATE_SUB(NOW(), INTERVAL 28 DAY), 1, 'Mures', 45, 'F', 2, 'Pensionar');
INSERT INTO entries(submission_id, kind, type, amount) VALUES (34, 'datorie', 'card credit', 13771);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (34, 'asset', 'depozite bancare', 94730);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (34, 'asset', 'investitii bursa', 116690);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (34, 'asset', 'imobile', 631370);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (34, 'asset', 'bunuri de valoare', 55646);
INSERT INTO submissions(id, uuid, session_id, created_at, optimist, judet, varsta, sex, persoane_intretinere, domeniu) VALUES (35, 'b5fc01f7-ec0d-4480-9b4c-0f5868eca868', 'ar5b9fg5', DATE_SUB(NOW(), INTERVAL 88 DAY), 1, 'Bucuresti', 31, 'X', 0, 'Freelance');
INSERT INTO entries(submission_id, kind, type, amount) VALUES (35, 'datorie', 'datorii la stat', 23899);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (35, 'datorie', 'datorii alte persoane', 6116);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (35, 'asset', 'depozite bancare', 117373);
INSERT INTO submissions(id, uuid, session_id, created_at, optimist, judet, varsta, sex, persoane_intretinere, domeniu) VALUES (36, 'cb5a782e-335b-4d16-b059-cfa88d81d787', 'dh2uyug3', DATE_SUB(NOW(), INTERVAL 67 DAY), 1, 'Buzau', 43, 'M', 1, 'Antreprenor / SRL');
INSERT INTO entries(submission_id, kind, type, amount) VALUES (36, 'datorie', 'credit personal', 59000);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (36, 'datorie', 'credit imobiliar', 585026);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (36, 'datorie', 'card credit', 3498);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (36, 'datorie', 'datorii la stat', 5876);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (36, 'asset', 'cryptomonede', 71421);
INSERT INTO submissions(id, uuid, session_id, created_at, optimist, judet, varsta, sex, persoane_intretinere, domeniu) VALUES (37, 'f77d539c-7e04-43cd-90ac-84dd9528bec6', 'm679vkzf', DATE_SUB(NOW(), INTERVAL 34 DAY), 1, 'Harghita', 40, 'F', 3, 'Comert');
INSERT INTO entries(submission_id, kind, type, amount) VALUES (37, 'datorie', 'credit personal', 40284);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (37, 'datorie', 'credit SRL', 183111);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (37, 'datorie', 'datorii la stat', 6573);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (37, 'datorie', 'datorii alte persoane', 17189);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (37, 'asset', 'titluri de stat', 26083);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (37, 'asset', 'investitii bursa', 69294);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (37, 'asset', 'cryptomonede', 5344);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (37, 'asset', 'bunuri de valoare', 30518);
INSERT INTO submissions(id, uuid, session_id, created_at, optimist, judet, varsta, sex, persoane_intretinere, domeniu) VALUES (38, 'a96fd39e-0759-42f2-9428-3f8bbf7cc63e', 'jthusb86', DATE_SUB(NOW(), INTERVAL 92 DAY), 0, 'Caras-Severin', 37, 'M', 2, 'Constructii');
INSERT INTO entries(submission_id, kind, type, amount) VALUES (38, 'datorie', 'credit imobiliar', 127729);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (38, 'asset', 'depozite bancare', 36988);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (38, 'asset', 'titluri de stat', 36977);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (38, 'asset', 'investitii bursa', 67149);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (38, 'asset', 'bunuri de valoare', 19372);
INSERT INTO submissions(id, uuid, session_id, created_at, optimist, judet, varsta, sex, persoane_intretinere, domeniu) VALUES (39, '27786d4a-58d6-4e90-9a55-ed83dd252b8d', 'dm9mhjvm', DATE_SUB(NOW(), INTERVAL 93 DAY), 0, 'Olt', 54, 'F', 1, 'Agricultura');
INSERT INTO entries(submission_id, kind, type, amount) VALUES (39, 'datorie', 'credit personal', 12165);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (39, 'datorie', 'credit imobiliar', 166481);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (39, 'asset', 'imobile', 211005);
INSERT INTO submissions(id, uuid, session_id, created_at, optimist, judet, varsta, sex, persoane_intretinere, domeniu) VALUES (40, '746bc1fc-ffe4-47ac-8f35-6a66fc8163fd', 'c6nkxp5c', DATE_SUB(NOW(), INTERVAL 42 DAY), 1, 'Galati', 65, 'X', 2, 'IT & Software');
INSERT INTO entries(submission_id, kind, type, amount) VALUES (40, 'datorie', 'credit personal', 69734);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (40, 'datorie', 'credit SRL', 240641);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (40, 'datorie', 'card credit', 11583);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (40, 'asset', 'titluri de stat', 12249);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (40, 'asset', 'investitii bursa', 75951);
INSERT INTO submissions(id, uuid, session_id, created_at, optimist, judet, varsta, sex, persoane_intretinere, domeniu) VALUES (41, '97807a6b-b387-4687-a8c7-8b63b2a38c55', 'nug5kv32', DATE_SUB(NOW(), INTERVAL 40 DAY), 0, 'Suceava', 37, 'X', 1, 'Comert');
INSERT INTO entries(submission_id, kind, type, amount) VALUES (41, 'datorie', 'datorii alte persoane', 6370);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (41, 'asset', 'terenuri', 23264);
INSERT INTO submissions(id, uuid, session_id, created_at, optimist, judet, varsta, sex, persoane_intretinere, domeniu) VALUES (42, 'b5ba8c7e-e0ab-4b7c-afa5-c9e286481b8b', 'us6e6b3u', DATE_SUB(NOW(), INTERVAL 22 DAY), 1, 'Dolj', 50, 'F', 3, 'Sanatate');
INSERT INTO entries(submission_id, kind, type, amount) VALUES (42, 'datorie', 'datorii alte persoane', 31158);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (42, 'asset', 'investitii bursa', 41458);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (42, 'asset', 'cryptomonede', 16384);
INSERT INTO submissions(id, uuid, session_id, created_at, optimist, judet, varsta, sex, persoane_intretinere, domeniu) VALUES (43, '2cccbc1c-5ef7-4989-b609-0784a8c3b40b', 'bc2xtsss', DATE_SUB(NOW(), INTERVAL 102 DAY), 0, 'Buzau', 28, 'X', 1, 'Student');
INSERT INTO entries(submission_id, kind, type, amount) VALUES (43, 'datorie', 'credit imobiliar', 240441);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (43, 'datorie', 'card credit', 5446);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (43, 'asset', 'investitii bursa', 50155);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (43, 'asset', 'cryptomonede', 6633);
INSERT INTO submissions(id, uuid, session_id, created_at, optimist, judet, varsta, sex, persoane_intretinere, domeniu) VALUES (44, '1e6dd552-85ca-4cb6-88d7-b0b96337ae19', '55bwtpbd', DATE_SUB(NOW(), INTERVAL 101 DAY), 1, 'Prahova', 36, 'X', 1, 'Freelance');
INSERT INTO entries(submission_id, kind, type, amount) VALUES (44, 'datorie', 'credit imobiliar', 250716);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (44, 'datorie', 'credit SRL', 243133);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (44, 'datorie', 'datorii la stat', 11966);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (44, 'datorie', 'datorii alte persoane', 4626);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (44, 'asset', 'investitii bursa', 86376);
INSERT INTO submissions(id, uuid, session_id, created_at, optimist, judet, varsta, sex, persoane_intretinere, domeniu) VALUES (45, '7c583ee0-ea6a-4da1-99c5-1cde9baaba30', '42n8tshs', DATE_SUB(NOW(), INTERVAL 31 DAY), 1, 'Bistrita-Nasaud', 36, 'X', 1, 'Administratie publica');
INSERT INTO entries(submission_id, kind, type, amount) VALUES (45, 'datorie', 'credit imobiliar', 182709);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (45, 'datorie', 'card credit', 11285);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (45, 'datorie', 'datorii alte persoane', 15673);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (45, 'asset', 'investitii bursa', 44795);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (45, 'asset', 'cryptomonede', 29958);
INSERT INTO submissions(id, uuid, session_id, created_at, optimist, judet, varsta, sex, persoane_intretinere, domeniu) VALUES (46, '0a223dbe-d709-4688-b6df-7ddda2db716d', 'cz26hnsh', DATE_SUB(NOW(), INTERVAL 95 DAY), 0, 'Arad', 54, 'F', 4, 'Educatie');
INSERT INTO entries(submission_id, kind, type, amount) VALUES (46, 'datorie', 'credit SRL', 18457);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (46, 'asset', 'depozite bancare', 72130);
INSERT INTO submissions(id, uuid, session_id, created_at, optimist, judet, varsta, sex, persoane_intretinere, domeniu) VALUES (47, '12a97680-e269-47c7-b820-2a85f865c4a7', 'smt6hybu', DATE_SUB(NOW(), INTERVAL 113 DAY), 0, 'Braila', 61, 'F', 2, 'Administratie publica');
INSERT INTO entries(submission_id, kind, type, amount) VALUES (47, 'datorie', 'credit personal', 47403);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (47, 'datorie', 'credit SRL', 128001);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (47, 'datorie', 'datorii alte persoane', 4791);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (47, 'asset', 'depozite bancare', 21027);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (47, 'asset', 'titluri de stat', 10023);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (47, 'asset', 'bunuri de valoare', 28446);
INSERT INTO submissions(id, uuid, session_id, created_at, optimist, judet, varsta, sex, persoane_intretinere, domeniu) VALUES (48, '13cf0919-048f-4c05-8ff0-35e2b1c7132f', 'z48mxhfw', DATE_SUB(NOW(), INTERVAL 52 DAY), 0, 'Galati', 45, 'X', 1, 'Agricultura');
INSERT INTO entries(submission_id, kind, type, amount) VALUES (48, 'datorie', 'credit imobiliar', 197992);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (48, 'datorie', 'card credit', 6130);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (48, 'datorie', 'datorii la stat', 20298);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (48, 'datorie', 'datorii alte persoane', 3699);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (48, 'asset', 'depozite bancare', 22283);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (48, 'asset', 'titluri de stat', 33372);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (48, 'asset', 'cryptomonede', 47357);
INSERT INTO submissions(id, uuid, session_id, created_at, optimist, judet, varsta, sex, persoane_intretinere, domeniu) VALUES (49, '52246363-253e-48de-a357-c9920ed42784', 'w3b8ndya', DATE_SUB(NOW(), INTERVAL 48 DAY), 1, 'Alba', 41, 'M', 4, 'Comert');
INSERT INTO entries(submission_id, kind, type, amount) VALUES (49, 'datorie', 'credit imobiliar', 449683);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (49, 'datorie', 'credit SRL', 124453);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (49, 'datorie', 'card credit', 3428);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (49, 'datorie', 'datorii alte persoane', 3460);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (49, 'asset', 'depozite bancare', 156145);
INSERT INTO submissions(id, uuid, session_id, created_at, optimist, judet, varsta, sex, persoane_intretinere, domeniu) VALUES (50, 'f1dfee54-d84b-44c4-9d0e-2d9470640e3f', 'xbrrp34v', DATE_SUB(NOW(), INTERVAL 118 DAY), 0, 'Bistrita-Nasaud', 50, 'X', 2, 'Industrie');
INSERT INTO entries(submission_id, kind, type, amount) VALUES (50, 'datorie', 'credit imobiliar', 282211);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (50, 'asset', 'depozite bancare', 41996);
INSERT INTO entries(submission_id, kind, type, amount) VALUES (50, 'asset', 'imobile', 626937);
